name: git hub actions sample

on: [push]

jobs:
  sample-job1:
    runs-on: ubuntu-latest
    steps:
      - name: Check Job 1 steps
        run: echo "Welcome All"
  sample-job2:
    runs-on: ubuntu-latest
    steps:
      - name: check job 2 steps or repository in-build environments
        run: |
          pwd
          ls -lrt
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
      - name: Cloing git repository
        uses: actions/checkout@v2
        with:
          ref: testing_actions
      - name: Checking our repository
        run: |
          pwd
          ls -a
          ls -lrt
